spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    topics:
      reserve-stock: reserve-stock-topic
      stock-reservation-result: stock-reservation-result-topic

server:
  port: 8081